export const mockMenuItems = {
  items: [
    {
      id: '1',
      name: 'Mixed Veg Soup',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Soup',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 85,
      bestSeller: true,
    },
    {
      id: '2',
      name: 'Mushroom Soup',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Soup',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 95,
      bestSeller: false,
    },
    {
      id: '3',
      name: 'Chicken Soup',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Soup',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 105,
      bestSeller: true,
    },
    {
      id: '4',
      name: 'Prawn Soup',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Soup',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 125,
      bestSeller: false,
    },
    {
      id: '5',
      name: 'Mutton Soup',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Soup',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 115,
      bestSeller: false,
    },
    {
      id: '6',
      name: 'Panner Butter Masala',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 189,
      bestSeller: true,
    },
    {
      id: '7',
      name: 'Mushroom Masala',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 195,
      bestSeller: false,
    },
    {
      id: '8',
      name: 'Gobi Masala',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 179,
      bestSeller: false,
    },
    {
      id: '9',
      name: 'Aloo Gobi',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 162,
      bestSeller: false,
    },
    {
      id: '10',
      name: 'Baby Corn Pepper Masala',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 210,
      bestSeller: false,
    },
    {
      id: '11',
      name: 'Mixed Veg Gravy',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 228,
      bestSeller: false,
    },
    {
      id: '12',
      name: 'Dal Fry',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 120,
      bestSeller: true,
    },
    {
      id: '13',
      name: 'Chilly Potato',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 138,
      bestSeller: false,
    },
    {
      id: '14',
      name: 'Gobi Manchurian',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 162,
      bestSeller: false,
    },
    {
      id: '15',
      name: 'Gobi 65',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 150,
      bestSeller: false,
    },
    {
      id: '16',
      name: 'Mushroom Manchurian',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 180,
      bestSeller: false,
    },
    {
      id: '17',
      name: 'Mushroom 65',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 170,
      bestSeller: true,
    },
    {
      id: '18',
      name: 'Baby Corn Manchurian',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 200,
      bestSeller: false,
    },
    {
      id: '19',
      name: 'Baby Corn 65',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 200,
      bestSeller: false,
    },
    {
      id: '20',
      name: 'Crispy Fried Vegetables',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Veg Starters',
      availability: ['LUNCH', 'DINNER'],
      price: 190,
      bestSeller: false,
    },
    {
      id: '21',
      name: 'Egg Curry',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 109,
      bestSeller: false,
    },
    {
      id: '22',
      name: 'Butter Chicken Masala',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 209,
      bestSeller: true,
    },
    {
      id: '23',
      name: 'Chicken Gravy',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 171,
      bestSeller: false,
    },
    {
      id: '24',
      name: 'Prawn Pepper Masala',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 239,
      bestSeller: false,
    },
    {
      id: '25',
      name: 'Kadaai Chicken',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 185,
      bestSeller: false,
    },
    {
      id: '26',
      name: 'Chettinadu Chicken',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 209,
      bestSeller: true,
    },
    {
      id: '27',
      name: 'Pepper Chicken Gravy',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 200,
      bestSeller: false,
    },
    {
      id: '28',
      name: 'Mutton Chettinadu',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 305,
      bestSeller: false,
    },
    {
      id: '29',
      name: 'Mutton Chukka',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Non Veg Main Course',
      availability: ['LUNCH', 'DINNER'],
      price: 315,
      bestSeller: false,
    },
    {
      id: '30',
      name: 'Veg Fried Rice',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 123,
      bestSeller: false,
    },
    {
      id: '31',
      name: 'Gobi Fried Rice',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 149,
      bestSeller: false,
    },
    {
      id: '32',
      name: 'Mushroom Fried Rice',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 179,
      bestSeller: false,
    },
    {
      id: '33',
      name: 'Paneer Fried Rice',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 161,
      bestSeller: true,
    },
    {
      id: '34',
      name: 'Veg Noodles',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 123,
      bestSeller: false,
    },
    {
      id: '35',
      name: 'Gobi Noodles',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 149,
      bestSeller: false,
    },
    {
      id: '36',
      name: 'Mushroom Noodles',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 179,
      bestSeller: true,
    },
    {
      id: '37',
      name: 'Paneer Noodles',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 161,
      bestSeller: false,
    },
    {
      id: '38',
      name: 'Egg Fried Rice',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 129,
      bestSeller: false,
    },
    {
      id: '39',
      name: 'Chicken Fried Rice',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 149,
      bestSeller: true,
    },
    {
      id: '40',
      name: 'Prawn Fried Rice',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 219,
      bestSeller: false,
    },
    {
      id: '41',
      name: 'Fish Fried Rice',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 229,
      bestSeller: false,
    },
    {
      id: '42',
      name: 'Egg Noodles',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 129,
      bestSeller: false,
    },
    {
      id: '43',
      name: 'Chicken Noodles',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 149,
      bestSeller: false,
    },
    {
      id: '44',
      name: 'Prawn Noodles',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 219,
      bestSeller: false,
    },
    {
      id: '45',
      name: 'Fish Noodles',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Fried Rice & Noodles',
      availability: ['LUNCH', 'DINNER'],
      price: 229,
      bestSeller: false,
    },
    {
      id: '46',
      name: 'Plain Roti',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 25,
      bestSeller: false,
    },
    {
      id: '47',
      name: 'Butter Roti',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 29,
      bestSeller: true,
    },
    {
      id: '48',
      name: 'Garlic Roti',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 42,
      bestSeller: false,
    },
    {
      id: '49',
      name: 'Plain Naan',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 40,
      bestSeller: false,
    },
    {
      id: '50',
      name: 'Butter Nann',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 60,
      bestSeller: false,
    },
    {
      id: '51',
      name: 'Garlic Naan',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Breads',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 70,
      bestSeller: true,
    },
    {
      id: '52',
      name: 'Tandoori Chicken Half',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Tandoori Items',
      availability: ['LUNCH', 'DINNER'],
      price: 240,
      bestSeller: true,
    },
    {
      id: '53',
      name: 'Pepper Barbeque Half',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Tandoori Items',
      availability: ['LUNCH', 'DINNER'],
      price: 240,
      bestSeller: false,
    },
    {
      id: '54',
      name: 'Chicken Kebabf',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Tandoori Items',
      availability: ['LUNCH', 'DINNER'],
      price: 180,
      bestSeller: false,
    },
    {
      id: '55',
      name: 'Grill Chicken half',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Tandoori Items',
      availability: ['LUNCH', 'DINNER'],
      price: 240,
      bestSeller: true,
    },
    {
      id: '56',
      name: 'Mojito',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 75,
      bestSeller: false,
    },
    {
      id: '57',
      name: 'Kiwi Crush',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 75,
      bestSeller: false,
    },
    {
      id: '58',
      name: 'Strawberry Crush',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 75,
      bestSeller: true,
    },
    {
      id: '59',
      name: 'Litchie',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 75,
      bestSeller: false,
    },
    {
      id: '60',
      name: 'Black Current tail',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 85,
      bestSeller: false,
    },
    {
      id: '61',
      name: 'Lemon Soda',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Mocktails',
      availability: ['BREAKFAST', 'LUNCH', 'DINNER'],
      price: 60,
      bestSeller: true,
    },
    {
      id: '62',
      name: 'Chicken Briyani',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 160,
      bestSeller: true,
    },
    {
      id: '63',
      name: 'Chicken 65 Briyani',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 200,
      bestSeller: false,
    },
    {
      id: '64',
      name: 'Egg Briyani',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 120,
      bestSeller: false,
    },
    {
      id: '65',
      name: 'Mutton Briyani',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 280,
      bestSeller: true,
    },
    {
      id: '66',
      name: 'Veg Briyani',
      type: 'Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 230,
      bestSeller: false,
    },
    {
      id: '67',
      name: 'Fish Briyani',
      type: 'Non-Veg',
      cuisine: 'South Indian',
      subType: 'Briyani',
      availability: ['LUNCH', 'DINNER'],
      price: 220,
      bestSeller: false,
    },
  ],
};
