export const orderList = [
  {
    id: '1',
    name: 'Mixed Veg Soup',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Soup',
    price: 85,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '2',
    name: 'Mushroom Soup',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Soup',
    price: 95,
    orderDate: '7/8/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '3',
    name: 'Chicken Soup',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Soup',
    price: 105,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 2,
  },
  {
    id: '4',
    name: 'Prawn Soup',
    type: 'Non-Veg',
    cuisine: 'North Indian',
    subType: 'Soup',
    price: 125,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '5',
    name: 'Mutton Soup',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Soup',
    price: 115,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '6',
    name: 'Panner Butter Masala',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Veg Main Course',
    price: 189,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '7',
    name: 'Mushroom Masala',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Main Course',
    price: 195,
    orderDate: '7/8/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '8',
    name: 'Gobi Masala',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Main Course',
    price: 179,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '9',
    name: 'Aloo Gobi',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Veg Main Course',
    price: 162,
    orderDate: '7/3/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 5,
  },
  {
    id: '10',
    name: 'Baby Corn Pepper Masala',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Main Course',
    price: 210,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 3,
  },
  {
    id: '11',
    name: 'Mixed Veg Gravy',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Main Course',
    price: 228,
    orderDate: '6/27/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 4,
  },
  {
    id: '12',
    name: 'Dal Fry',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Veg Main Course',
    price: 120,
    orderDate: '6/16/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '13',
    name: 'Chilly Potato',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 138,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '14',
    name: 'Gobi Manchurian',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 162,
    orderDate: '7/4/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '15',
    name: 'Gobi 65',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 150,
    orderDate: '7/7/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 6,
  },
  {
    id: '16',
    name: 'Mushroom Manchurian',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Veg Starters',
    price: 180,
    orderDate: '7/8/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '17',
    name: 'Mushroom 65',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 170,
    orderDate: '6/30/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '18',
    name: 'Baby Corn Manchurian',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Veg Starters',
    price: 200,
    orderDate: '6/24/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 3,
  },
  {
    id: '19',
    name: 'Baby Corn 65',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 200,
    orderDate: '6/21/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '20',
    name: 'Crispy Fried Vegetables',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Veg Starters',
    price: 190,
    orderDate: '7/6/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '21',
    name: 'Egg Curry',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 109,
    orderDate: '7/7/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 5,
  },
  {
    id: '22',
    name: 'Butter Chicken Masala',
    type: 'Non-Veg',
    cuisine: 'North Indian',
    subType: 'Non Veg Main Course',
    price: 209,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 4,
  },
  {
    id: '23',
    name: 'Chicken Gravy',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 171,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '24',
    name: 'Prawn Pepper Masala',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 239,
    orderDate: '6/19/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '25',
    name: 'Kadaai Chicken',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 185,
    orderDate: '6/27/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '26',
    name: 'Chettinadu Chicken',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 209,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 5,
  },
  {
    id: '27',
    name: 'Pepper Chicken Gravy',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 200,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '28',
    name: 'Mutton Chettinadu',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 305,
    orderDate: '6/13/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 3,
  },
  {
    id: '29',
    name: 'Mutton Chukka',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Non Veg Main Course',
    price: 315,
    orderDate: '6/13/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '30',
    name: 'Veg Fried Rice',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 123,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 4,
  },
  {
    id: '31',
    name: 'Gobi Fried Rice',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 149,
    orderDate: '7/4/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '32',
    name: 'Mushroom Fried Rice',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Fried Rice & Noodles',
    price: 179,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '33',
    name: 'Paneer Fried Rice',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 161,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '34',
    name: 'Veg Noodles',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 123,
    orderDate: '7/7/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '35',
    name: 'Gobi Noodles',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 149,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '36',
    name: 'Mushroom Noodles',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 179,
    orderDate: '6/13/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 4,
  },
  {
    id: '37',
    name: 'Paneer Noodles',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Fried Rice & Noodles',
    price: 161,
    orderDate: '6/25/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '38',
    name: 'Egg Fried Rice',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 129,
    orderDate: '6/25/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '39',
    name: 'Chicken Fried Rice',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 149,
    orderDate: '6/24/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 7,
  },
  {
    id: '40',
    name: 'Prawn Fried Rice',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 219,
    orderDate: '6/29/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '41',
    name: 'Fish Fried Rice',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 229,
    orderDate: '7/10/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '42',
    name: 'Egg Noodles',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 129,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '43',
    name: 'Chicken Noodles',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 149,
    orderDate: '7/8/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 4,
  },
  {
    id: '44',
    name: 'Prawn Noodles',
    type: 'Non-Veg',
    cuisine: 'North Indian',
    subType: 'Fried Rice & Noodles',
    price: 219,
    orderDate: '7/7/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '45',
    name: 'Fish Noodles',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Fried Rice & Noodles',
    price: 229,
    orderDate: '7/6/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '46',
    name: 'Plain Roti',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Breads',
    price: 25,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 10,
  },
  {
    id: '47',
    name: 'Butter Roti',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Breads',
    price: 29,
    orderDate: '7/4/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 7,
  },
  {
    id: '48',
    name: 'Garlic Roti',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Breads',
    price: 42,
    orderDate: '7/3/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 4,
  },
  {
    id: '49',
    name: 'Plain Naan',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Breads',
    price: 40,
    orderDate: '7/2/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 3,
  },
  {
    id: '50',
    name: 'Butter Nann',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Breads',
    price: 60,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 7,
  },
  {
    id: '51',
    name: 'Garlic Naan',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Breads',
    price: 70,
    orderDate: '6/24/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 5,
  },
  {
    id: '52',
    name: 'Tandoori Chicken Half',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Tandoori Items',
    price: 240,
    orderDate: '7/11/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '53',
    name: 'Pepper Barbeque Half',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Tandoori Items',
    price: 240,
    orderDate: '7/11/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '54',
    name: 'Chicken Kebabf',
    type: 'Non-Veg',
    cuisine: 'North Indian',
    subType: 'Tandoori Items',
    price: 180,
    orderDate: '7/7/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 5,
  },
  {
    id: '55',
    name: 'Grill Chicken half',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Tandoori Items',
    price: 240,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '56',
    name: 'Mojito',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 75,
    orderDate: '7/6/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '57',
    name: 'Kiwi Crush',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 75,
    orderDate: '7/6/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
  {
    id: '58',
    name: 'Strawberry Crush',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 75,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 3,
  },
  {
    id: '59',
    name: 'Litchie',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 75,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '60',
    name: 'Black Current tail',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 85,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '61',
    name: 'Lemon Soda',
    type: 'Veg',
    cuisine: 'South Indian',
    subType: 'Mocktails',
    price: 60,
    orderDate: '7/9/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 1,
  },
  {
    id: '62',
    name: 'Chicken Briyani',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Briyani',
    price: 160,
    orderDate: '7/11/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 15,
  },
  {
    id: '63',
    name: 'Chicken 65 Briyani',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Briyani',
    price: 200,
    orderDate: '7/3/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 6,
  },
  {
    id: '64',
    name: 'Egg Briyani',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Briyani',
    price: 120,
    orderDate: '7/4/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '65',
    name: 'Mutton Briyani',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Briyani',
    price: 280,
    orderDate: '7/1/2022',
    orderTime: '1:30:55 PM',
    bestSeller: true,
    quantity: 8,
  },
  {
    id: '66',
    name: 'Veg Briyani',
    type: 'Veg',
    cuisine: 'North Indian',
    subType: 'Briyani',
    price: 230,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 1,
  },
  {
    id: '67',
    name: 'Fish Briyani',
    type: 'Non-Veg',
    cuisine: 'South Indian',
    subType: 'Briyani',
    price: 220,
    orderDate: '7/5/2022',
    orderTime: '1:30:55 PM',
    bestSeller: false,
    quantity: 2,
  },
];
